name: "Setup environment"

runs:
  using: composite
  steps:
    # ensure checkout step is run before calling this action
    - uses: 'moonrepo/setup-toolchain@v0'
      with:
        auto-install: true
    - run: pnpm install
      shell: bash