name: "Setup environment"

runs:
  name: "Setup environment"
  using: composite
  steps:
    - uses: 'moonrepo/setup-toolchain@v0'
      with:
        auto-install: true
    - run: pnpm install
      shell: bash