name: "Create GitHub release"

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  test:
    steps:
      - name: "Setup environment"
        uses: ./.github/actions/setup
      - run: pnpm test

  build:
    name: "Build ${{ matrix.browser }} extension"
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        browser: [ chrome, firefox ]
    steps:
      - name: "Setup environment"
        uses: ./.github/actions/setup
      - run: pnpm build:${{ matrix.browser }}
      - name: "Create zip archive"
        run: |
          cd dist/${{ matrix.browser }}
          zip -r ../../${{matrix.browser}}_extension.zip .
      - name: Archive production artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.browser }}
          path: ${{ matrix.browser }}_extension.zip

  publish:
    name: Publish build artifacts
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Download build artifacts"
        uses: actions/download-artifact@v4

      - name: "List files"
        run: ls -R

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            firefox/firefox_extension.zip
            chrome/chrome_extension.zip
