name: "Create GitHub release"

on:
  push:
#    tags:
#      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  test:
    uses: ./.github/workflows/setup_run_pnpm.yml
    name: "Run tests"
    with:
      pnpm_command: "test"

  build:
    name: "Build ${{ matrix.browser }} extension"
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        browser: [ chrome, firefox ]
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'moonrepo/setup-toolchain@v0'
        with:
          auto-install: true
      - run: pnpm install
      - run: pnpm build:${{ matrix.browser }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.browser }}_extension
          path: dist/${{ matrix.browser }}

  publish:
    name: Publish build artifacts
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Download build artifacts"
        uses: actions/download-artifact@v4

      - name: "List files"
        run: ls -R

#      - name: Create GitHub Release
#        uses: softprops/action-gh-release@v2
#        with:
#          generate_release_notes: true
#          files: |
#            firefox_extension.zip
#            chrome_extension.zip
