name: "Validate Pull Request"

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v5'
      - uses: ./.github/actions/setup
      - run: pnpm test
