name: "Validate Pull Request"

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Setup environment"
        uses: ./.github/workflows/setup_env.yml
      - run: pnpm test
