runs:
  using: composite
  name: "Setup environment"
  steps:
    - uses: 'actions/checkout@v4'
    - uses: 'moonrepo/setup-toolchain@v0'
      with:
        auto-install: true
    - run: pnpm install
      shell: bash